"use client";

import { useEffect, useRef, useState } from "react";
import type { Location, Outbreak, RouteAssessment } from "@/lib/api";

const tileUrl = process.env.NEXT_PUBLIC_MAP_TILE_URL || "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const typeLabel = (type: Location["type"]) => type === "market" ? "Livestock market" : type.replaceAll("_", " ");

export function PilotGeographicMap({ locations, outbreaks, assessment }: { locations: Location[]; outbreaks: Outbreak[]; assessment?: RouteAssessment | null }) {
  const mapRef = useRef<HTMLDivElement>(null); const [tilesFailed, setTilesFailed] = useState(false); const [selected, setSelected] = useState<Location | null>(null);
  useEffect(() => { let map: import("leaflet").Map | undefined; let disposed = false; (async () => { const L = await import("leaflet"); if (!mapRef.current || disposed) return; const leafletMap = L.map(mapRef.current, { scrollWheelZoom: true, keyboard: true }); map = leafletMap; const points: [number, number][] = [];
    const tiles = L.tileLayer(tileUrl, { attribution: "&copy; OpenStreetMap contributors", maxZoom: 19 }); tiles.on("tileerror", () => setTilesFailed(true)); tiles.addTo(leafletMap);
    locations.forEach(location => { const point: [number, number] = [location.latitude, location.longitude]; points.push(point); const marker = L.circleMarker(point, { radius: location.type === "market" ? 9 : 7, color: "#0f766e", weight: 3, fillColor: "#fff", fillOpacity: 1 }).addTo(leafletMap); marker.bindTooltip(`${location.name} — ${typeLabel(location.type)}`); marker.on("click", () => setSelected(location)); });
    outbreaks.filter(x => x.status !== "closed").forEach(outbreak => { const point: [number, number] = [outbreak.location.latitude, outbreak.location.longitude]; points.push(point); const color = outbreak.status === "confirmed" ? "#b42318" : "#b45309"; L.circleMarker(point, { radius: 10, color, weight: 3, fillOpacity: .35 }).addTo(leafletMap).bindTooltip(`${outbreak.status}: ${outbreak.location.name}`); if (outbreak.review_radius_km) L.circle(point, { radius: outbreak.review_radius_km * 1000, color, weight: 2, fillOpacity: .08 }).addTo(leafletMap); });
    const geometry = assessment?.route_geometry; if (geometry?.length) { const route = geometry.map(([lng, lat]) => [lat, lng] as [number, number]); route.forEach(x => points.push(x)); L.polyline(route, { color: "#0f8b8d", weight: 5, opacity: .92 }).addTo(leafletMap); }
    if (points.length) leafletMap.fitBounds(L.latLngBounds(points), { padding: [32, 32], maxZoom: 13 }); else leafletMap.setView([20, 78], 5);
  })(); return () => { disposed = true; map?.remove(); }; }, [locations, outbreaks, assessment]);
  return <div className="space-y-3"><div className="relative h-[420px] overflow-hidden rounded-xl border border-line bg-[#e8eee8]"><div ref={mapRef} className="absolute inset-0" aria-label="Interactive pilot geographic map" />{tilesFailed && <div className="absolute inset-x-3 bottom-3 z-[500] rounded-lg border border-line bg-white/95 p-3 text-sm font-semibold">Map tiles are unavailable. Local-coordinate markers and route geometry remain visible.</div>}</div><p className="text-sm leading-6 text-slate-700">Pilot geography is based on coordinates manually entered by the local operations team. Road routes are informational and do not issue a movement permit, legal restriction, or veterinary decision.</p>{selected && <div role="status" className="rounded-lg border border-line bg-paper p-3 text-sm"><b>{selected.name}</b> · {typeLabel(selected.type)} · {selected.district}, {selected.state} · Pilot entered</div>}<p className="sr-only">Visible pilot records: {locations.map(x => x.name).join(", ") || "no locations"}. Active pilot outbreaks: {outbreaks.filter(x=>x.status!=="closed").map(x=>`${x.status} at ${x.location.name}`).join(", ") || "none"}. {assessment?.route_geometry ? "An informational road route is shown." : "No road route geometry is available."}</p></div>;
}
