"use client";

import { CheckCircle2, LoaderCircle } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { type Location, type LocationDataSource, type Outbreak } from "@/lib/api";
import { useDataContext } from "@/lib/data-context";
import { loadLocationReferences } from "@/lib/location-references";
import { submitRegistration } from "@/lib/registration-submit";

const controls = "h-14 w-full rounded-xl border border-line bg-white px-4 text-base text-ink";
const symptoms = [
  ["fever", "Fever"], ["high_fever", "High fever"], ["oral_vesicles", "Oral vesicles"], ["foot_vesicles", "Foot vesicles"], ["excessive_salivation", "Excessive salivation"], ["lameness", "Lameness"], ["multiple_skin_nodules", "Multiple skin nodules"], ["swollen_lymph_nodes", "Swollen lymph nodes"], ["nasal_ocular_discharge", "Nasal/ocular discharge"], ["throat_submandibular_swelling", "Throat/submandibular swelling"], ["difficulty_breathing", "Difficulty breathing"], ["sudden_death", "Sudden death"], ["unclotted_bleeding", "Unclotted bleeding from body openings"], ["staggering", "Staggering"], ["crepitating_hindquarter_swelling", "Crepitating hindquarter muscle swelling"], ["oral_erosions", "Oral erosions"], ["oculonasal_discharge", "Oculonasal discharge"], ["diarrhea", "Diarrhea"], ["high_mortality_young", "High mortality in young animals"], ["late_term_abortion", "Late-term abortion"], ["retained_placenta", "Retained placenta"], ["reduced_fertility", "Reduced fertility"],
] as const;

export function RegisterSymptomReportForm() {
  const { context } = useDataContext(); const [source, setSource] = useState<LocationDataSource | "">(context === "all" ? "" : context); const [locations, setLocations] = useState<Location[]>([]); const [queued, setQueued] = useState(false); const [created, setCreated] = useState<Outbreak | null>(null); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (!source) return setLocations([]); loadLocationReferences(source).then(setLocations).catch((e: Error) => setError(e.message)); }, [source]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = form.getAll("symptoms").map(String); if (!selected.length) return setError("Select at least one symptom."); setSubmitting(true); const payload = { disease_name: "Symptom and mortality report", species: String(form.get("species")), status: "suspected", location_id: Number(form.get("location_id")), data_source: source, detected_at: new Date().toISOString(), suspected_cases: Number(form.get("animals_affected")), confirmed_cases: 0, mortality_count: Number(form.get("mortality_count")), verification_level: "reported", symptoms: selected, days_since_onset: Number(form.get("days_since_onset")), reporter_type: String(form.get("reporter_type")), animals_affected: Number(form.get("animals_affected")) }; const result = await submitRegistration<Outbreak>("create_outbreak", payload, id => `/outbreaks/${id}`); result.kind === "central" ? setCreated(result.entity) : setQueued(true); setSubmitting(false); }
  if (queued) return <Card className="max-w-2xl p-7 text-center"><CheckCircle2 className="mx-auto text-risk-amber" size={40}/><h2 className="mt-4 font-display text-3xl font-semibold">Saved on this device. Pending sync.</h2><p className="mt-3 text-sm">This report has not reached the central database yet.</p></Card>;
  if (created) return <Card className="max-w-2xl p-7 text-center"><CheckCircle2 className="mx-auto text-risk-green" size={40}/><h2 className="mt-4 font-display text-3xl font-semibold">Report recorded</h2><p className="mt-3 text-sm">{created.disease_name}. Requires veterinary review; this triage does not confirm infection.</p><Link className="mt-6 inline-block text-teal underline" href="/">Return to dashboard</Link></Card>;
  return <Card className="max-w-4xl p-5 md:p-8"><form onSubmit={submit} className="space-y-6"><label className="block text-sm font-bold">Record context<select required value={source} disabled={context !== "all"} onChange={e => setSource(e.target.value as LocationDataSource)} className={`mt-2 ${controls}`}><option value="" disabled>Select context</option><option value="demo_seed">Demo record</option><option value="pilot_entered">Pilot-entered record</option></select></label><p className="rounded-lg bg-[#FFF3E0] p-4 text-sm">Requires veterinary review; this triage does not confirm infection or issue an official alert.</p><div className="grid gap-5 md:grid-cols-2"><label>Location<select name="location_id" required className={`mt-2 ${controls}`}><option value="">Select location</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Species<select name="species" required className={`mt-2 ${controls}`}><option value="Cattle">Cattle</option><option value="Buffalo">Buffalo</option><option value="Goat">Goat</option><option value="Sheep">Sheep</option><option value="Pig">Pig</option><option value="Poultry">Poultry</option></select></label><label>Animals affected<input name="animals_affected" type="number" min="1" required className={`mt-2 ${controls}`}/></label><label>Mortality count<input name="mortality_count" type="number" min="0" required className={`mt-2 ${controls}`}/></label><label>Days since onset<input name="days_since_onset" type="number" min="0" required className={`mt-2 ${controls}`}/></label><label>Reporter type<select name="reporter_type" required className={`mt-2 ${controls}`}><option value="farmer">Farmer</option><option value="field_worker">Field worker</option><option value="veterinary_officer">Veterinary officer</option></select></label></div><fieldset><legend className="text-sm font-bold">Symptoms</legend><div className="mt-3 grid gap-2 md:grid-cols-2">{symptoms.map(([value,label]) => <label key={value} className="flex gap-2 text-sm"><input type="checkbox" name="symptoms" value={value}/>{label}</label>)}</div></fieldset>{error && <p role="alert" className="text-risk-red">{error}</p>}<div className="flex justify-end"><Button disabled={submitting || !source || !locations.length}>{submitting && <LoaderCircle className="animate-spin" size={17}/>}Submit symptom / mortality report</Button></div></form></Card>;
}
