"use client";

import { ChevronDown, ShieldCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

export function WorkspaceSwitcher({ workspace }: { workspace: "operations" | "public" }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const first = useRef<HTMLAnchorElement>(null);
  useEffect(() => { const outside=(event:MouseEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",outside);document.removeEventListener("keydown",escape)};},[]);
  useEffect(()=>{if(open)requestAnimationFrame(()=>first.current?.focus())},[open]);
  const current=workspace==="operations"?"District Vet Team":"Animal Owner / Trader";
  return <div ref={root} className="relative"><button type="button" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex min-h-11 items-center gap-2 rounded-lg px-2 text-left hover:bg-ink/5"><span className={`grid h-8 w-8 place-items-center rounded-full text-white ${workspace==="operations"?"bg-teal":"bg-[#B45309]"}`}>{workspace==="operations"?<ShieldCheck size={16} aria-hidden="true"/>:<UsersRound size={16} aria-hidden="true"/>}</span><span className="hidden text-sm font-semibold md:inline">{current}</span><ChevronDown size={15} aria-hidden="true"/></button>{open&&<div role="menu" aria-label="Workspace views" className="absolute right-0 z-50 mt-2 w-80 rounded-xl border border-line bg-white p-2 shadow-xl"><p className="px-3 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">Workspace view — not a signed-in identity</p><Link ref={first} role="menuitem" href="/" onClick={()=>setOpen(false)} className={`block rounded-lg p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal ${workspace==="operations"?"bg-paper":"hover:bg-paper"}`}><span className="flex items-center gap-2 font-bold"><ShieldCheck size={16} aria-hidden="true"/>District Vet Team</span><span className="mt-1 block text-xs leading-5 text-slate-600">Outbreak response, advisories, tracing and review</span></Link><Link role="menuitem" href="/movement-check" onClick={()=>setOpen(false)} className={`mt-1 block rounded-lg p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal ${workspace==="public"?"bg-paper":"hover:bg-paper"}`}><span className="flex items-center gap-2 font-bold"><UsersRound size={16} aria-hidden="true"/>Animal Owner / Trader</span><span className="mt-1 block text-xs leading-5 text-slate-600">Pre-travel movement check for owners, buyers and transporters</span></Link></div>}</div>;
}
